---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluebuild-test
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # add system tools
  - type: dnf
    install:
      packages:
        - fish
        - ncdu
        - ranger

  - type: akmods
    base: main
    install:
      - framework-laptop
      - v4l2loopback
      - zfs

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship

  - type: script
    scripts:
      - vscode-install.sh

  - type: script
    scripts:
      - kde-setup.py

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
